# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\repos\PlagueLyrics\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 842)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.S0 = QtWidgets.QTextEdit(self.centralWidget)
        self.S0.setGeometry(QtCore.QRect(10, 30, 51, 31))
        self.S0.setObjectName("S0")
        self.N0 = QtWidgets.QTextEdit(self.centralWidget)
        self.N0.setGeometry(QtCore.QRect(190, 30, 51, 31))
        self.N0.setObjectName("N0")
        self.BPM0 = QtWidgets.QTextEdit(self.centralWidget)
        self.BPM0.setGeometry(QtCore.QRect(70, 30, 51, 31))
        self.BPM0.setObjectName("BPM0")
        self.Start = QtWidgets.QPushButton(self.centralWidget)
        self.Start.setGeometry(QtCore.QRect(10, 70, 231, 31))
        self.Start.setObjectName("Start")
        self.OutList = QtWidgets.QListWidget(self.centralWidget)
        self.OutList.setGeometry(QtCore.QRect(510, 110, 481, 731))
        self.OutList.setObjectName("OutList")
        self.LyricsList = QtWidgets.QTextEdit(self.centralWidget)
        self.LyricsList.setGeometry(QtCore.QRect(10, 110, 481, 731))
        self.LyricsList.setObjectName("LyricsList")
        self.Beats0 = QtWidgets.QTextEdit(self.centralWidget)
        self.Beats0.setGeometry(QtCore.QRect(130, 30, 51, 31))
        self.Beats0.setObjectName("Beats0")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(130, 10, 47, 13))
        self.label_4.setObjectName("label_4")
        self.Export = QtWidgets.QPushButton(self.centralWidget)
        self.Export.setGeometry(QtCore.QRect(510, 70, 231, 31))
        self.Export.setObjectName("Export")
        self.FileName = QtWidgets.QTextEdit(self.centralWidget)
        self.FileName.setGeometry(QtCore.QRect(260, 70, 231, 31))
        self.FileName.setObjectName("FileName")
        self.Open = QtWidgets.QPushButton(self.centralWidget)
        self.Open.setGeometry(QtCore.QRect(760, 70, 111, 31))
        self.Open.setObjectName("Open")
        self.Save = QtWidgets.QPushButton(self.centralWidget)
        self.Save.setGeometry(QtCore.QRect(880, 70, 111, 31))
        self.Save.setObjectName("Save")
        self.Beats1 = QtWidgets.QTextEdit(self.centralWidget)
        self.Beats1.setGeometry(QtCore.QRect(380, 30, 51, 31))
        self.Beats1.setObjectName("Beats1")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(440, 10, 47, 13))
        self.label_5.setObjectName("label_5")
        self.N1 = QtWidgets.QTextEdit(self.centralWidget)
        self.N1.setGeometry(QtCore.QRect(440, 30, 51, 31))
        self.N1.setObjectName("N1")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(380, 10, 47, 13))
        self.label_6.setObjectName("label_6")
        self.BPM1 = QtWidgets.QTextEdit(self.centralWidget)
        self.BPM1.setGeometry(QtCore.QRect(320, 30, 51, 31))
        self.BPM1.setObjectName("BPM1")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(320, 10, 47, 13))
        self.label_7.setObjectName("label_7")
        self.Beats2 = QtWidgets.QTextEdit(self.centralWidget)
        self.Beats2.setGeometry(QtCore.QRect(630, 30, 51, 31))
        self.Beats2.setObjectName("Beats2")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(690, 10, 47, 13))
        self.label_8.setObjectName("label_8")
        self.N2 = QtWidgets.QTextEdit(self.centralWidget)
        self.N2.setGeometry(QtCore.QRect(690, 30, 51, 31))
        self.N2.setObjectName("N2")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(630, 10, 47, 13))
        self.label_9.setObjectName("label_9")
        self.BPM2 = QtWidgets.QTextEdit(self.centralWidget)
        self.BPM2.setGeometry(QtCore.QRect(570, 30, 51, 31))
        self.BPM2.setObjectName("BPM2")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(570, 10, 47, 13))
        self.label_10.setObjectName("label_10")
        self.Beats3 = QtWidgets.QTextEdit(self.centralWidget)
        self.Beats3.setGeometry(QtCore.QRect(880, 30, 51, 31))
        self.Beats3.setObjectName("Beats3")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(940, 10, 47, 13))
        self.label_11.setObjectName("label_11")
        self.N3 = QtWidgets.QTextEdit(self.centralWidget)
        self.N3.setGeometry(QtCore.QRect(940, 30, 51, 31))
        self.N3.setObjectName("N3")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(880, 10, 47, 13))
        self.label_12.setObjectName("label_12")
        self.BPM3 = QtWidgets.QTextEdit(self.centralWidget)
        self.BPM3.setGeometry(QtCore.QRect(820, 30, 51, 31))
        self.BPM3.setObjectName("BPM3")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(820, 10, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(260, 10, 47, 13))
        self.label_14.setObjectName("label_14")
        self.S1 = QtWidgets.QTextEdit(self.centralWidget)
        self.S1.setGeometry(QtCore.QRect(260, 30, 51, 31))
        self.S1.setObjectName("S1")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(510, 10, 47, 13))
        self.label_15.setObjectName("label_15")
        self.S2 = QtWidgets.QTextEdit(self.centralWidget)
        self.S2.setGeometry(QtCore.QRect(510, 30, 51, 31))
        self.S2.setObjectName("S2")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(760, 10, 47, 13))
        self.label_16.setObjectName("label_16")
        self.S3 = QtWidgets.QTextEdit(self.centralWidget)
        self.S3.setGeometry(QtCore.QRect(760, 30, 51, 31))
        self.S3.setObjectName("S3")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plague\'s Lyrics to .srt"))
        self.Start.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "Steps"))
        self.label_3.setText(_translate("MainWindow", "BPM"))
        self.label_4.setText(_translate("MainWindow", "Maat"))
        self.Export.setText(_translate("MainWindow", "Export to .srt"))
        self.Open.setText(_translate("MainWindow", "Open"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "Steps"))
        self.label_6.setText(_translate("MainWindow", "Maat"))
        self.label_7.setText(_translate("MainWindow", "BPM"))
        self.label_8.setText(_translate("MainWindow", "Steps"))
        self.label_9.setText(_translate("MainWindow", "Maat"))
        self.label_10.setText(_translate("MainWindow", "BPM"))
        self.label_11.setText(_translate("MainWindow", "Steps"))
        self.label_12.setText(_translate("MainWindow", "Maat"))
        self.label_13.setText(_translate("MainWindow", "BPM"))
        self.label_14.setText(_translate("MainWindow", "Start"))
        self.label_15.setText(_translate("MainWindow", "Start"))
        self.label_16.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

